name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: build docker image for IRIS
      run: docker build -t intersystemsdc/iris-community:2019.4.0.383.0-zpm .
    - name: push IRIS to docker hub 
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push intersystemsdc/iris-community:2019.4.0.383.0-zpm
    
    - name: build docker image for IRIS4H
      run: docker build --build-arg IMAGE=store/intersystems/irishealth-community:2019.4.0.383.0 -t intersystemsdc/irishealth-community:2019.4.0.383.0-zpm-dev .
    - name: push IRIS4H to docker hub 
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push intersystemsdc/irishealth-community:2019.4.0.383.0-zpm-dev
    
    - uses: actions/checkout@master
    - name: build docker image for IRIS - dev mode
      run: docker build --build-arg DEV=1 -t intersystemsdc/iris-community:2019.4.0.383.0-zpm-dev .
    - name: push IRIS to docker hub 
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push intersystemsdc/iris-community:2019.4.0.383.0-zpm-dev
    
    - name: build docker image for IRIS4H - dev mode
      run: docker build --build-arg DEV=1 IMAGE=store/intersystems/irishealth-community:2019.4.0.383.0 -t intersystemsdc/irishealth-community:2019.4.0.383.0-zpm-dev .
    - name: push IRIS4H to docker hub 
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push intersystemsdc/irishealth-community:2019.4.0.383.0-zpm-dev