name: CI

on: 
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - release

jobs:
  build:
    strategy:
      matrix:
        version:          
          # latest stable
          - tag: 2022.1.0.209.0
            latest: true
            image: iris-community
          - tag: 2022.1.0.209.0
            latest: true
            image: irishealth-community
          - tag: 2022.1.0.209.0
            latest: true
            image: iris-ml-community

          - tag: 2021.2.0.651.0
            image: iris-community
          - tag: 2021.2.0.651.0
            image: irishealth-community
          - tag: 2021.2.0.651.0
            image: iris-ml-community
          - tag: 2021.2.0.651.0
            image: irishealth-ml-community
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master

    - name: build docker image for ${{ matrix.version.image }}:${{ matrix.version.tag }}
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        retry_on: timeout
        command: |
          docker build --build-arg IMAGE=containers.intersystems.com/intersystems/${{ matrix.version.image }}:${{ matrix.version.tag }} \
           -t intersystemsdc/${{ matrix.version.image }}:${{ matrix.version.tag }}-zpm .
    - name: inspect docker image size
      run: |
        docker history intersystemsdc/${{ matrix.version.image }}:${{ matrix.version.tag }}-zpm
        docker images -f label=org.opencontainers.image.vendor=InterSystems
    - name: push intersystemsdc/${{ matrix.version.image }}:${{ matrix.version.tag }}-zpm to docker hub 
      if: github.event.repository.fork == false
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push intersystemsdc/${{ matrix.version.image }}:${{ matrix.version.tag }}-zpm
    - name: latest version
      if: github.event.repository.fork == false && matrix.version.latest
      run: |
        docker tag intersystemsdc/${{ matrix.version.image }}:${{ matrix.version.tag }}-zpm intersystemsdc/${{ matrix.version.image }}:latest
        docker push intersystemsdc/${{ matrix.version.image }}:latest
    - name: preview version
      if: github.event.repository.fork == false && matrix.version.preview
      run: |
        docker tag intersystemsdc/${{ matrix.version.image }}:${{ matrix.version.tag }}-zpm intersystemsdc/${{ matrix.version.image }}:preview
        docker push intersystemsdc/${{ matrix.version.image }}:preview
