name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        image: [
        "iris-community:2020.3.0.221.0",
        "irishealth-community:2020.3.0.221.0",
        "iris-community:2020.2.0.204.0",
        "irishealth-community:2020.2.0.204.0",
        "iris-aa-community:2020.4.0AA.368.0"
        ]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
  
    - name: build docker image for ${{ matrix.image }}
      run: docker build --build-arg IMAGE=store/intersystems/${{ matrix.image }} -t intersystemsdc/${{ matrix.image }}-zpm .
    - name: push ${{ matrix.image }} to docker hub 
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push intersystemsdc/${{ matrix.image }}-zpm
    
