name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        image: [
        "iris-community:2020.3.0.221.0",
        "irishealth-community:2020.3.0.221.0",
        "iris-community:2020.4.0.524.0",
        "irishealth-community:2020.4.0.524.0",
        "iris-ml-community:2020.3.0.302.0"
        ]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
  
    - name: build docker image for ${{ matrix.image }}
      run: docker build --build-arg IMAGE=store/intersystems/${{ matrix.image }} -t intersystemsdc/${{ matrix.image }}-zpm .
    - name: inspect docker image size
      run: |
        docker history intersystemsdc/${{ matrix.image }}-zpm
        docker images -f label=org.opencontainers.image.vendor=InterSystems
    - name: push intersystemsdc/${{ matrix.image }}-zpm to docker hub 
      if: github.event.repository.fork == false
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push intersystemsdc/${{ matrix.image }}-zpm
    
